name: ⚡ Coverage badges generation

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage-badges-generation:
    name: 📣 Coverage badges generation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: 📦 Setup bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: ⎔ Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: ./package.json

      - name: 📥 Install deps
        run: bun install --frozen-lockfile

      - name: 🔍 Tests
        run: bun test-ci

      - name: ⚙️ Building action
        run: bun run build

      - name: 😼 Generating coverage badges
        id: local-action-run
        uses: ./
        with:
          badges-icon: vitest
          badges-labels-prefix: "Test coverage –"
          commit-message: "chore: updating coverage badges"
          commit-user: jpb06
          commit-user-email: jpb.06@outlook.com