name: ⚡ Live tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage-badges-generation:
    name: 🧑‍🔬 Build action and run transpiled output
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: 📦 Setup bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: ⎔ Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: ./package.json

      - name: 📥 Install deps
        run: bun install --frozen-lockfile

      - name: 🔍 Tests
        run: bun test-ci

      - name: ⚙️ Building action
        run: bun run build

      - name: ❎ Remove badges
        run: rm -rf ./badges

      - name: 😼 Running action
        id: local-action-run
        uses: ./
        with:
          badges-icon: vitest
          badges-labels-prefix: "Repo test coverage"
          commit-message: "chore: updating coverage badges"
          commit-user: jpb06
          commit-user-email: jpb.06@outlook.com
          no-commit: true